# Generated by Django 5.2 on 2025-05-01 08:31

import Staff.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0004_alter_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Task Given', 'Task Given'), ('In Progress', 'In Progress'), ('Stuck in Error', 'Stuck in Error'), ('Completed', 'Completed')], max_length=50)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=Staff.models.default_end_time)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='task_screenshots/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='task_screenshots/')),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.task')),
            ],
        ),
    ]
