# Generated by Django 5.2 on 2025-04-26 16:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_manager_salary'),
        ('Manager', '0002_alter_attendance_staff_alter_leaveapplication_staff_and_more'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 17, 21, 53, 499328, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='task_screenshots/')),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
