# Generated by Django 5.2 on 2025-04-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_alter_task_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 16, 50, 45, 849276, tzinfo=datetime.timezone.utc)),
        ),
    ]
