# Generated by Django 5.2 on 2025-04-30 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_alter_task_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 20, 30, 40, 815903, tzinfo=datetime.timezone.utc)),
        ),
    ]
