# Generated by Django 5.2 on 2025-04-25 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('hiring_manager', models.CharField(max_length=100)),
                ('vacancies', models.PositiveIntegerField()),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('experience_required', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager')], max_length=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('payslip', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records_as_manager', to='Authentication.manager')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records_as_staff', to='Authentication.staff')),
            ],
        ),
    ]
