# Generated by Django 5.2 on 2025-05-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
