# Generated by Django 5.2 on 2025-04-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
    ]
