# Generated by Django 5.2 on 2025-04-29 04:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_manager_user'),
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='in_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='task',
            name='out_time',
            field=models.TimeField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='screenshot_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.manager'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Task Given', 'Task Given'), ('In Progress', 'In Progress'), ('Stuck in Error', 'Stuck in Error'), ('Completed', 'Completed')], default='Task Given', max_length=20),
        ),
    ]
