# Generated by Django 5.2 on 2025-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_attendance_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
