# Generated by Django 5.2 on 2025-04-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_alter_attendance_staff_alter_leaveapplication_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
